# Generated by Django 2.2.5 on 2019-12-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtail_opengraph_image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphimage',
            name='image',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='wagtailimages.Image',
            ),
        ),
        migrations.AlterField(
            model_name='opengraphimage',
            name='page',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='wagtailcore.Page',
            ),
        ),
        migrations.CreateModel(
            name='OpenGraphImageGeneratorSettings',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'company_logo',
                    models.ForeignKey(
                        blank=True,
                        help_text='Will be added to the top left of every OpenGraph image',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wagtailimages.Image',
                    ),
                ),
                (
                    'company_logo_alternative',
                    models.ForeignKey(
                        blank=True,
                        help_text='Alternative version of your logo the dark variant OpenGraph variant. You may want to supply a differently colored logo.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wagtailimages.Image',
                    ),
                ),
                (
                    'default_background_image',
                    models.ForeignKey(
                        blank=True,
                        help_text='Will be used as a fallback background image for your OpenGraph images if no model specific image field has been defined',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='wagtailimages.Image',
                    ),
                ),
                (
                    'site',
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='wagtailcore.Site',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
    ]
