# Generated by Django 3.0.3 on 2020-04-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtail_opengraph_image_generator', '0002_auto_20191212_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphimagegeneratorsettings',
            name='company_logo',
            field=models.ForeignKey(blank=True, help_text='Will be added to the top left of every OpenGraph image.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='opengraphimagegeneratorsettings',
            name='company_logo_alternative',
            field=models.ForeignKey(blank=True, help_text='Alternative version of your logo for the dark OpenGraph image variant. You may want to supply a differently colored logo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='opengraphimagegeneratorsettings',
            name='default_background_image',
            field=models.ForeignKey(blank=True, help_text='Will be used as a fallback background image for your OpenGraph images if no model specific image field has been defined.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
